### ISSUE TITLE
Rename project files to Railway Relays Tester

### ISSUE THREAD

**Issue by leanfrancucci** [gicsafe-firmware/rrtester#1]
Before starting the development, it would be nice if the references to DIMBA project like files, directories and projects could be renamed using the name of this project.

**Comment by cmancon** [comment]
@leanfrancucci. The renaming should include IDE project configuration files? Or these are to be removed?

**Comment by cmancon** [comment]
Is there any work left to do about this issue?

**Comment by leanfrancucci** [comment]
I think tasks about that are done, so you can close this issue.

**Comment by cmancon** [comment]
I agree. Closing it. A "good first _closed_ Issue".
