### ISSUE TITLE
Possible message loss while reconnecting to Broker

### ISSUE THREAD

**Issue by cmancon** [gicsafe-firmware/rrtester#7]
The System's firmware uses the MQTT protocol to communicate regularly. To strengthen the communication, it implements ***Quality of Service 1***. By this, *the Client* (the device) **assures** that the *PUBLISH Packet is received at least once* by *the Broker* (the server).

A *QoS 1 PUBLISH Packet* has a *Packet Identifier* in its *variable header* and is acknowledged by a *PUBACK Packet*. The **Client must** treat the PUBLISH Packet as “unacknowledged” until it has received the corresponding PUBACK Packet from the receiver. Meanwhile, the Client will re-deliver the PUBLISH Packet (with DUP Flag set) among further PUBLISH Packets.

In situations in which the communication link was unstable, it was observed that some message loss was occurring. It's especially critical the sequence: PUBLISH Packet and disconnection before the PUBACK Packet arrives.

**Comment by cmancon** [comment]
This issue relates to https://github.com/gicsafe-firmware/dimba/issues/1

**Comment by cmancon** [comment]
A branch was created to work in this issue: [issue/7-PossibleMessageLoss](https://github.com/gicsafe-firmware/rrtester/tree/issue/7-PossibleMessageLoss)

**Comment by cmancon** [comment]
A routine of Publish & Disconnect was implemented to simulate the situation described above.

![ForcePublication Disconnect](https://user-images.githubusercontent.com/28371239/61186944-d483c000-a641-11e9-9b6f-ffaa4e4f7881.PNG)

In this image we can see:
* The Socket connection (packets 73-80)
* The CONNECT Packet from the Client to the Broker (packet 114).
* The CONNACK Packet from the Broker to the Client (packet 116).
* Forced PUBLISH Packet with ID=46161. (packet 204).
* PUBACK Packet from the Broker (packet 211) not processed by the firmware because the SM has transitioned to the 'waitServer' state (in ConMgrEth).
* The Disconnection from the Broker and the reconnection afterwards (packets 212-302).
* The PUBLISH Packet with ID=60968. **Here we can see the loss of the ID=46161 Packet. Although the Client is allowed to send further PUBLISH Packets, no attempt to send the non acknowledged Packet was made**.

**Comment by cmancon** [comment]
If we analyze how MQTTProt works, we can find the reason of the loss:

![MQTTProt_UML](https://raw.githubusercontent.com/gicsafe-firmware/dimbaUML/master/modelConcept/MQTT.PNG)

During the reconnection, the Client will enter the 'TryConnect' state, executing the entry '[brokerConnect()](https://github.com/gicsafe-firmware/rrtester/blob/485710d46200adcd2f8ec787918cfa7bca19199d/src/mqttProt/mqttProt.c#L689-L701)':
```
static void 
brokerConnect(MQTTProt *const me, RKH_EVT_T *pe)
{
	(void)pe;


    mqtt_init(&me->client, 0, me->sendbuf, sizeof(me->sendbuf), 
              me->recvbuf, sizeof(me->recvbuf), 0);
    me->operRes = mqtt_connect(&me->client, 
                               me->config->clientId, 
                               NULL, NULL, 0, NULL, NULL, 0, 
                               me->config->keepAlive);
    me->errorStr = mqtt_error_str(me->operRes);
}
```
The call to '[mqtt_init()](https://github.com/leanfrancucci/MQTT-C/blob/37c7d49090544e8eeb74c9fe878f1376a11d0547/src/mqtt.c#L45-L78)' calls '[mqtt_mq_init()](https://github.com/leanfrancucci/MQTT-C/blob/37c7d49090544e8eeb74c9fe878f1376a11d0547/src/mqtt.c#L2031-L2039)' later on, re-initializing the message queue of packets to send.

**On each reconnection, the Packet buffer is cleared, thus losing the non-acknowleged PUBLISH Packets.**

If the `mqtt_init()` is called once at the initial action '[init()](https://github.com/gicsafe-firmware/rrtester/blob/485710d46200adcd2f8ec787918cfa7bca19199d/src/mqttProt/mqttProt.c#L385)' we can avoid the re-initialization of the message queue on each reconnection.

**Comment by cmancon** [comment]
After moving the initialization of the MQTT library in fa254a70eb84471c970d681a07ccb92972542128, the previous test was executed resulting in the following:

![ForcePublication DisconnectMalformed](https://user-images.githubusercontent.com/28371239/61187837-2aaa3080-a64d-11e9-9b59-3156c16411c0.PNG)

As we can see, we have the connection, publish and disconnection sequence as before but when the client gets reconnected, it sends a PUBLISH Packet (packet 598) that the *Network Protocol Analyzer" can't fully interpret. Later on, another PUBLISH Packet (packet 733) is sent but again is interpreted as malformed, having two difference IDs.

**In close inspection, we can see that the packet 598 has the same overall length of the initial PUBLISH Packet (packet 205). And it was confirmed that both had the same ID in the Variable Header, but the packet is somehow malformed**.

This behavior was confirmed with two different Brokers, both closing the connection on the Broker side (packets 736-747). In fact, the Client would reconnect and try to send the same malformed packet, entering a loop.

**Comment by cmancon** [comment]
Suspecting some error while packing the PUBLISH Packet to be re-delivered, an [output log](https://github.com/gicsafe-firmware/rrtester/blob/a89c7af57cbe6c477b184af9c4f2705c4522f7d6/src/arch/linux/bsp/eth.c#L449-L458) is used to check it.

The standard [says](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718038):

> The DUP flag MUST be set to 1 by the Client or Server when it attempts to re-deliver a PUBLISH Packet

So we have to expect the **same PUBLISH Packet with the DUP flag set**.

As we are inspecting the log file in an hex editor, we should see a a change from `0x32` to `0x3A` in the beginning of the Packet.

![ForcePublication DisconnectMalformedHexa](https://user-images.githubusercontent.com/28371239/61191010-75db3800-a67b-11e9-81e4-955b4a4ae877.png)

In the image, it's shown that the MQTT duplicated Packet not only doesn't have the DUP flag set (Fixed header starts with `0x32`) but the [Remaining Length field](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718038) is modified without reason. The value difference between the packets is 8, this could indicate that the DUP flag is being set in the 2nd byte of the Fixed Header.

In the following snippet from the [MQTT library](https://github.com/leanfrancucci/MQTT-C/blob/37c7d49090544e8eeb74c9fe878f1376a11d0547/src/mqtt.c#L483-L494) shows the bug when setting the DUP flag with the wrong array index (first the 1st byte of the fixed header is addressed with index 0, and later on with index 1):
```
            case MQTT_CONTROL_PUBLISH:
                local->inspected = 0x03 & ((local->msg->start[0]) >> 1); /* qos */
                if (local->inspected == 0) {
                    local->msg->state = MQTT_QUEUED_COMPLETE;
                } else if (local->inspected == 1) {
                    local->msg->state = MQTT_QUEUED_AWAITING_ACK;
                    /*set DUP flag for subsequent sends */ 
                    local->msg->start[1] |= MQTT_PUBLISH_DUP;
                } else {
                    local->msg->state = MQTT_QUEUED_AWAITING_ACK;
                }
                break;
```

**Comment by cmancon** [comment]
After modifying the corresponding [line](https://github.com/leanfrancucci/MQTT-C/blob/37c7d49090544e8eeb74c9fe878f1376a11d0547/src/mqtt.c#L490), i.e. correcting the index of the array, the Publish&Disconnect test is run again:

![ForcePublication DisconnectModifiedLibrary](https://user-images.githubusercontent.com/28371239/61256604-c918bd80-a743-11e9-88f0-884ee3858108.PNG)

This is a particularly good example. First we can see that the PUBACK Packet (packet 251) arrives after the disconnection of the Client, clearing all doubts of the need to re-deliver the packet. Later on, after the reconnection a PUBLISH Packet (packet 786) is sent. The ID is the same of the initial PUBLISH Packet, the Fixed Header starts with `0x3A` and, as it is shown by the Network Protocol Analyzer (on the Header Flags drop-down) this means that the DUP Flag was correctly set. Also as the remaining field has a value of `0xD3` (or `0b11010011`) if the DUP Flag were misplaced, the field would have a value of `0xDB` (or `0b11011011`).

Finally, we can see a new PUBLISH Packet being sent (packet 872). This is the first of the next messages to be sent to the Broker.

From these results, we can infer that the Broker was disconnecting a misbehaving Client after the malformed Packets were received. The actual policy to deal with this cases is not yet clear (for the author of this comment), but if the disconnection happens on the arrival of a new Packet after the malformed one, it seems like the Broker is trying to reassemble the first Packet with 8 bytes from the next one, leading to a severely malformed second Packet.

**Comment by cmancon** [comment]
A Pull Request (https://github.com/LiamBindle/MQTT-C/pull/40) was made to the original author of the library, pending the fix in the fork used in this repository.

**Comment by cmancon** [comment]
A Pull Request (https://github.com/leanfrancucci/MQTT-C/pull/1) was made to the MQTT-C forked Sub-Module.

**Comment by LiamBindle** [comment]
Hi @cmancon, let me know if you have any questions that I could help with.
> On each reconnection, the Packet buffer is cleared, thus losing the non-acknowleged PUBLISH Packets.

Yeah, this is a limitation of MQTT-C. Currently, unacknowledged packets are destroyed during a reconnect. I'd be open to talking about a fix for this if it's necessary.

**Comment by cmancon** [comment]
Implemented proposed fix in https://github.com/gicsafe-firmware/rrtester/commit/de3dbcfd44e7585d67dcaebc1c0954f24908545e and https://github.com/gicsafe-firmware/rrtester/commit/ee58700994eebaf4eb92c97cb96eefe443e0db7e. Closing as fixed.
